volumes:
  postgres_volume_local:
  assets_volume:
  contracts_volume:

services:
  # Сервис для приложения
  app:
    container_name: mall-tenants
    build:
      context: ./backend 
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}" 
      - "${SWAGGER_PORT}:${SWAGGER_PORT}" 
    volumes:
      - assets_volume:/app/assets/floor_plans
      - contracts_volume:/app/contracts/final
    depends_on:
      db:
        condition: service_healthy
    restart: always
    env_file:
      - .env
  client:
    container_name: mall-client
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_PORT}:80"
    depends_on:
      - app
    env_file:
      - .env

  # Сервис для PostgreSQL
  db:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
    ports:
      - "${DB_PORT}:${DB_PORT_INTERNAL}" 
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d ${DB_DB}'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  # Сервис для миграций
  migrate:
    container_name: migrator
    build:
      context: ./backend
      dockerfile: migration.Dockerfile
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
    env_file:
      - .env

